name: 'Blog_It'
author: 'Azanul Haque'
description: 'Allows you to reflect your latest activity on any markdown file using RSS feed.'

inputs:
  url:
    description: 'RSS url to fetch events from'
    required: true

  max_number_of_posts:
    description: 'Max number of posts to fetch from the RSS feed'
    default: 5

  target_md:
    description: 'Target .md file to update'
    default: 'README.md'

  gh_token:
    description: 'GitHub access token with Repo scope'
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.gh_token }}

    - name: Fetch Github Release Asset
      uses: dsaltares/fetch-gh-release-asset@1.1.0
      with:
        repo: "Azanul/BlogIt"
        version: 'tags/test4'
        file: blog_it

    - name: Run
      run: ./blog_it --url {{ inputs.url }} --number-of-posts {{ inputs.max_number_of_posts }}
      shell: bash

    - name: Commit and push if README changed
      run: |-
        git diff
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "README-bot"
        git diff --quiet || (git add README.md && git commit -m "Updated README")
        git push
      shell: bash

branding:
  icon: 'edit-3'
  color: 'yellow'